DATASET:
  CLASS: UEADataset
  PARAM:
    name: ArticularyWordRecognition
    path: ~/data/UEA
  fs: 200
EXPERIMENT:
  BATCH_SIZE: 16
  EPOCHS: 200
  OPTIMIZER:
    CLASS: SGD
    PARAM:
      lr: 0.0001
      momentum: 0.9
      weight_decay: 0.0005
  SCHEDULER:
    CLASS: ReduceLROnPlateau
    PARAM:
      cooldown: 0
      eps: 8.0e-09
      factor: 0.5
      min_lr: 1.0e-06
      mode: min
      patience: 10
      threshold: 4.0e-05
      threshold_mode: rel
      verbose: false
GRAPH:
  ADJ_MATRIX: complete
  NODE: raw
MODEL:
  CLASS: ChebNet
  PARAM:
    dropout: 0.5
    graphlearn: false
    hidden_dim: 128
    len: 144
    in_dim: 144
    mlp_dim: 128
    n_classes: 25
    k: 2
    n_layers: 3
    residual: false
SYSTEM:
  GPU: 7
  NUM_WORKERS: 10
  SEED: 42