DATASET:
  CLASS: UEADataset
  PARAM:
    name: ArticularyWordRecognition
    path: ~/data/UEA
  fs: 200
EXPERIMENT:
  BATCH_SIZE: 128
  EPOCHS: 200
  OPTIMIZER:
    CLASS: SGD
    PARAM:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
  SCHEDULER:
    CLASS: ReduceLROnPlateau
    PARAM:
      cooldown: 0
      eps: 8.0e-09
      factor: 0.5
      min_lr: 1.0e-06
      mode: min
      patience: 10
      threshold: 4.0e-05
      threshold_mode: rel
      verbose: false
GRAPH:
  ADJ_MATRIX: complete
  NODE: raw
MODEL:
  CLASS: STGCN
  PARAM:
    dropout: 0.5
    graphlearn: false
    hidden_dim: 128
    len: 144
    in_dim: 144
    mlp_dim: 128
    t_embedding: 128
    k: 3
    n_classes: 25
    n_layers: 2
    residual: false
    readout: mean
SYSTEM:
  GPU: 7
  NUM_WORKERS: 10
  SEED: 42